### ISSUE TITLE
Refactor the whole REPO

### ISSUE THREAD

**Issue by darkRaspberry** [cestaSociety/hacktoberfest2021#1]
To be frank the whole repo is OLD. You can do like refactore all the website which is broken and have lots of bugs. Lots of bugs

Things you can do.
 - Although website is already broken in compoents. so simply segegrate all the repo.
    - Segregrate the website js and css to folder to make it look nice.
    - Update the all dependencies which is in the website like jquery or css and all the other things. And fix all the boken things.
    - think your self

**Comment by ironbatshashank** [comment]
@darkRaspberry this is a very bad practice of writing someone's work is not good enough, especially in a community that is so helping and is trying to do things for benefit of others.

Secondly, I understand your point and agree with you that this could use a little upgrade, would you like to take up this issue? I can assign you this.

Also, keep in mind that this was designed with the purpose of making people contribute without feeling overwhelmed by the complexity of the project. A little structure would surely benefit, but too much branching will just leave people in bewilderment, resulting in them giving up. Also, the packages surely need an upgrade because this was designed more than a year ago and there hasn't been any major change to it.

This is a repo for everyone to easily understand and contribute whatever and however, they can.

**Comment by darkRaspberry** [comment]
Well I'm very very much have the same opinion.
 
The point which I was making that "its old". Simply, a good and working app become less useful after some time. (no offence) because there are other much more updated apps are there. Well I did write shit that word. And that a valid offence which i did. sorry for that.

This task is very much overwhelmed. Which i have clealy written already as Label - **"[Master] Bug" - This bug need my core energy and a quantum tunnel to solve.** The label description says that all.

Also, user can always create a new issue which user themselves can fix.

**Comment by darkRaspberry** [comment]
I have created 3 types of label for issues, which have 3 complexity. User can choose and create issues which they want.
Also I had very less time to make it live and working. There are other members which will create issues with lower complexities. Hope that helps.
Feel free to Add/Modify/Delete anything which you are concerned about. I According to my calculation you already have write access of the repo
